apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $CLUSTER_NAME
  region: $REGION
  version: "$CLUSTER_VERSION"

managedNodeGroups:
  - name: ng-1
    instanceType: $MACHINE_TYPE
    desiredCapacity: $DESIRED_SIZE
    minSize: $MIN_SIZE
    maxSize: $MAX_SIZE
    volumeSize:
    privateNetworking: true

availabilityZones: ['us-east-1a', 'us-east-1b']
